name: Terraform Main

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "envs/dev/**"
      - "modules/**"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  TF_VERSION: "1.15.4"
  AWS_REGION: "us-east-1"

jobs:
  apply:
    name: Plan and Apply Dev
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        working-directory: envs/dev

    concurrency:
      group: terraform-dev
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # Create this secret after creating the GitHub Actions OIDC role in AWS.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -input=false -out=tfplan

      - name: Terraform apply
        run: terraform apply -input=false -auto-approve tfplan
